### PR TITLE
remove docs build and create a .gitignore for the docs

### PR DESCRIPTION
**Pull request by basnijholt**
Build files shouldn't be stored in the repo (only source).

It's also relatively easy to set-up an automatic build on `qms.readthedocs.io`, if you want them to be easily accessible.

### CODE REVIEW

**Comment by donjan** [comment]
These were left for somebody (who isn't me, on account of not being a MS employee) to compare/move to an official DockerHub account.
Removing is of course correct, but afaict we still don't publish our documentation.

**Comment by basnijholt** [comment]
If I will have (make) time soon, I can set up automatic builds on qmt.readthedocs.io.

To generate the docs, it should just be `cd docs; make html`

**Comment by donjan** [comment]
I didn't figure how to nicely build the apidoc from a clean slate with just `make html`, but I guess you can just pack it into subprocess calls.

**Comment by basnijholt** [comment]
One can also just checkout this commit: https://github.com/Microsoft/qmt/tree/60cae5f297b4def7503a3c21be7d709235116d5a/doc/_build/html

**Pull request merged**
