### PR TITLE
Updated geometry_sweep example

### PR DESCRIPTION
**Pull request by adamfrees**
Updated geometry_sweep so it now works with current code.

- Changed the inputs to the build_3d_geometry function to match current version
- Removed Dask from example

### CODE REVIEW

**Comment by likewei92** [comment]
Remember to run black (do `black [path to qmt] -y py36`) and you'll pass the linting check :)

**Comment by adamfrees** [comment]
Great, thanks Kewei!

**Comment by likewei92** [comment]
FYI I prefer squash merges to keep the master commit history a bit cleaner :)

Also remember to delete your branch if you're done with it? :P

**Comment by adamfrees** [comment]
Got it! I'll do a squash merge next time :-)

**Pull request merged**
